name: 'Podman Build & Push (GCR)'
description: 'Build and Push action for Google Container Registry'

inputs:
  host:  # id of input
    description: 'registry host'
    required: false 
    default: 'gcr.io'
  project_id:
    description: 'project id'
    required: true
  access_token:
    description: "oauth2accesstoken"
    required: true
  image_id: 
    description: "image tag name" 
    required: true

runs:
  using: "composite"
  steps:
    - name: Google Container Registry Authorization
      run: echo ${{ inputs.access_token }} | podman login -u oauth2accesstoken --password-stdin ${{ inputs.host }}
      shell: bash

    - name: Build and Push
      run: podman build . -t ${{ host }}/${{ project_id }}/${{ inputs.image_id }} | podman push ${{ host }}/${{ project_id }}/${{ inputs.image_id }}
      shell: bash
